trigger:
  branches:
    include: [master]
  tags:
    include: ["*"]

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
  - template: job--python-tox.yml@sloria
    parameters:
      toxenvs: [lint, py37, py37-ptpython, py310, docs]
      os: linux
  - template: job--pypi-release.yml@sloria
    parameters:
      dependsOn:
        - tox_linux
