trigger:
  branches:
    include: [master]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs: [lint, py36, py36-ptpython, py37, py38, py39, docs]
    os: linux
- template: job--pypi-release.yml@sloria
  parameters:
    dependsOn:
      - tox_linux
