[tox]
envlist = lint,py310-ptpythonlowest,py310-lowest,py310,py311,py312,py313,py314,py314-ptpython,docs

[testenv]
dependency_groups = tests
deps =
    ptpythonlowest: ptpython==3.0.0
    ptpython: ptpython>=3.0.0
    lowest: ipython==8.0.0
commands = pytest {posargs}

[testenv:lint]
deps = pre-commit~=4.0
skip_install = true
commands = pre-commit run --all-files

[testenv:docs]
extras = docs
commands = sphinx-build docs/ docs/_build {posargs}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
deps = sphinx-autobuild
extras = docs
commands = sphinx-autobuild --port=0 docs/ docs/_build {posargs} --watch src

[testenv:readme-serve]
deps = restview
skip_install = true
commands = restview README.rst
